### PR TITLE
Fix errors in database readme

### PR DESCRIPTION
**Pull request by Timiport**
I noticed that I got the method descriptions and parameters mixed up in the readme. Fixed in this PR.

### CODE REVIEW

**Review by JackyXu-Cool — COMMENTED** [review]
LG!

**Comment by JackyXu-Cool** [comment]
Thanks for working on it! Feel free to merge it before the code review deadline

**Review by JackyXu-Cool — APPROVED** [review]

**Review by lhyelinn — APPROVED** [review]

**Comment by lhyelinn** [comment]
kudos for great work!

**Comment by hloneal** [comment]
Great catches, looks good!

**Pull request merged**
