### PR TITLE
Added test for naive bayes

### PR DESCRIPTION
**Pull request by lhyelinn**
Added tests for naive_bayes()

### CODE REVIEW

**Comment by Timiport** [comment]
Good Work! This LGTM.

**Comment by ruokun-niu** [comment]
Quick question: Is there a need to modify the NB function so that it accepts a random seed? Just curious as I'm not really familiar  with NB

**Review by ruokun-niu — APPROVED** [review]

**Comment by lhyelinn** [comment]
> Quick question: Is there a need to modify the NB function so that it accepts a random seed? Just curious as I'm not really familiar with NB

Yes, we can include random seed as part of separating the dataset into training set and testing set. Since this is not necessary in all case of naive bayes, I modified the code to use random seed only when it's given.

**Comment by ruokun-niu** [comment]
Naisu! Approved!

**Review by hloneal — COMMENTED** [review]
Good handling of the seed

**Pull request merged**
