### PR TITLE
Implemented Kmeans

### PR DESCRIPTION
**Pull request by ruokun-niu**
Kmeans is a relatively easy-to-implement algorithm and I believe that it is a great starting point. Only `numpy` was used and no new external imports are needed. Please follow [these instructions](https://github.com/JackyXu-Cool/Team-2130-Machine-Learning-Roulette/blob/master/mlr_backend/README.MD) for setting up environment.

This PR tracks issue #18. 
Functions Implemented:

- KMeans(): The core functionalities. Take in a dataset and an integer value of k. Returns a centroid of a Kmeans grouping and the datapoints that are associated with the centroid
- biKmeans(): A variation of Kmeans that resolves the local minimum problem
- randCent(): helper function for creating a centroid
- distEuclid(): Calculates the euclidean distance between two vectors

Tests will be added soon (maybe in a separate PR)

### CODE REVIEW

**Comment by JackyXu-Cool** [comment]
LGTM. Good job Tommy!

**Comment by ruokun-niu** [comment]
Restoring the branch for assignment purposes

**Comment by mmmmarty** [comment]
Reviewed and great job

**Review by hloneal — COMMENTED** [review]
Nice implementation! We should be able to use already existing libraries as well, so there is no need to build from the ground up like this.

**Comment by ruokun-niu** [comment]
@hloneal Yep I agree.
I'm gonna ask our client about using scipy for ML models during our next meeting.

For this algorithm, the client did provide some existing code so it's all right

**Pull request merged**
